### ISSUE TITLE
Script Search & Replace turn me an error when i update to the last v7.0.0.2

### ISSUE THREAD

**Issue by tercelazul** [luminescence-software/scripts#11]
Script Search & Replace turn me an error when i update to the last v7.0.0.2. The error image attached below. In the past version of Metatogger the same script is totally functional
![Metatogger 7 0 New Version](https://user-images.githubusercontent.com/36663078/105495250-5373a300-5c92-11eb-8f17-05272b394392.jpg)

**Comment by CyberSinh** [comment]
Hi

It is bug related to the new deployment option used in Metatogger 7 (`PublishSingleFile`). 
This option seems to be incompatible with Roslyn scripting.

So, I have just released a new version of Metatogger (v7.0.0.3) without this deployment feature.
Can you test this version and tell me if this issue is fixed?

Thanks.
